name: Build app and CodeQL analyze

on:
  push:
    branches: [ main, develop, devops ]
  pull_request:
    branches: [ main, develop, devops ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ javascript ]
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2 
        with:
          languages: ${{ matrix.language }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: build/ # or path/to/artifact